apiVersion: v1
kind: Secret
metadata:
  name: gremlinregistrykey
type: kubernetes.io/dockerconfigjson
data:
  {{ if .Values.openiam.image.credentialsJSON }}
  .dockerconfigjson: {{ template "imagePullSecretJSON" . }}
  {{ else }}
  .dockerconfigjson: {{ template "imagePullSecret" . }}
  {{end}}