apiVersion: v1
kind: Service
metadata:
  name: selfservice-ext
  labels:
{{ include "labels.standard" . | indent 4 }}
  annotations:
  {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: selfservice-ext
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    release: {{ .Release.Name }}
    app: {{ .Values.openiam.appname }}-selfservice-ext
