kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openiam-pvc-ldap-connector-rabbitmq
  labels:
    app: openiam-pvc-ldap-connector-rabbitmq
    openiam_collect_logs: 'true'
spec:
  accessModes:
  {{- range .Values.volumes.ldap_connector_rabbitmq.volume.ldap_connector_rabbitmq.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.ldap_connector_rabbitmq.volume.ldap_connector_rabbitmq.size | quote }}
{{- if .Values.volumes.ldap_connector_rabbitmq.volume.ldap_connector_rabbitmq.storageClass }}
{{- if (eq "-" .Values.volumes.ldap_connector_rabbitmq.volume.ldap_connector_rabbitmq.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.volumes.ldap_connector_rabbitmq.volume.ldap_connector_rabbitmq.storageClass }}"
{{- end }}
{{- end }}
