kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openiam-pvc-vault-storage
  labels:
    app: openiam-pvc-vault-storage
    openiam_collect_logs: 'true'
spec:
  accessModes:
  {{- range .Values.volumes.vault.volume.storage.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.vault.volume.storage.size | quote }}
{{- if .Values.volumes.vault.volume.storage.storageClass }}
{{- if (eq "-" .Values.volumes.vault.volume.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.volumes.vault.volume.storage.storageClass }}"
{{- end }}
{{- end }}
