apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openiam.appname }}-esb
  labels:
{{ include "labels.standard" . | indent 4 }}
  annotations:
  {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: esb
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    release: {{ .Release.Name }}
    app: {{ .Values.openiam.appname }}-esb
