apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.openiam.appname }}-machine-learning
  labels:
    openiam_collect_logs: 'true'
{{ include "labels.standard" . | indent 4 }}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: {{ .Values.openiam.appname }}-machine-learning
  serviceName: {{ .Values.openiam.appname }}-machine-learning
  replicas: {{ required "openiam.machine_learning.replicas is required" .Values.openiam.machine_learning.replicas }}
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
      {{- if .Values.openiam.machine_learning.podAnnotations }}
{{ toYaml .Values.openiam.machine_learning.podAnnotations | indent 8 }}
      {{- end }}
      labels:
        release: {{ .Release.Name }}
        app: {{ .Values.openiam.appname }}-machine-learning
        openiam_collect_logs: 'true'
        {{- range $key, $value := .Values.openiam.machine_learning.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      {{- if .Values.openiam.machine_learning.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.openiam.machine_learning.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.openiam.machine_learning.hostAliases }}
      hostAliases:
{{ toYaml .Values.openiam.machine_learning.hostAliases | indent 8 }}
      {{- end }}
      {{- if .Values.openiam.machine_learning.tolerations }}
      tolerations:
{{ toYaml .Values.openiam.machine_learning.tolerations | indent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.openiam.appname }}-machine-learning
            topologyKey: "kubernetes.io/hostname"
      securityContext:
{{ toYaml .Values.openiam.machine_learning.securityContext | indent 8 }}
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: machine-learning
        image: "{{ .Values.openiam.image.prefix }}/machine-learning:{{ .Values.openiam.image.version }}-{{ .Values.openiam.image.environment }}"
        imagePullPolicy: {{ .Values.openiam.image.pullPolicy }}
        env:
        - name: TZ
          value: {{ .Values.global.timezone | quote }}
        - name: OPENIAM_LOG_LEVEL
          value: {{ .Values.openiam.bash.log.level }}
        - name: LOGGING_LEVEL
          value: {{ .Values.openiam.bash.log.level }}
        - name: RABBITMQ_HOST
          value: {{ .Values.openiam.rabbitmq.host | quote }}
        - name: RABBITMQ_PORT
          value: {{ .Values.openiam.rabbitmq.port | quote }}
        - name: VAULT_HOST
          value: {{ .Values.openiam.vault.url | quote }}
        - name: VAULT_KEYPASS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: vaultKeyPassword
        readinessProbe:
          exec:
            command: ['/bin/sh', '-c', '(healthcheck.sh 120 && exit 0) || exit 1']
          initialDelaySeconds: 120
          timeoutSeconds: 120
          periodSeconds: 60
          failureThreshold: 6
        livenessProbe:
          exec:
            command: ['/bin/sh', '-c', '(healthcheck.sh 120 && exit 0) || exit 1']
          initialDelaySeconds: 120
          timeoutSeconds: 120
          periodSeconds: 60
          failureThreshold: 6
        resources:
{{ toYaml .Values.openiam.machine_learning.resources | indent 10 }}
        volumeMounts:
        - mountPath: /data/openiam/conf/ai
          name: openiam-pvc-storage-machine-learning
        - mountPath: /data/openiam/conf/vault/server
          name: vault-server-config
          readOnly: true
        - mountPath: /data/openiam/conf/vault/client
          name: vault-client-config
          readOnly: true
{{- if .Values.openiam_rabbitmq.rabbitmq.tls.enabled }}
        - mountPath: /data/openiam/conf/rabbitmq/client
          name: openiam-pvc-rabbitmq-jks
          readOnly: true
        - mountPath: /data/openiam/conf/rabbitmq/server
          name: rabbitmq-certificates
          readOnly: true
{{- end }}
      initContainers:
      - name: volumeinit
        image: "{{ .Values.openiam.image.prefix }}/chown:{{ .Values.openiam.image.version }}-{{ .Values.openiam.image.environment }}"
        imagePullPolicy: {{ .Values.openiam.image.pullPolicy }}
        securityContext:
          runAsUser: {{ .Values.global.volumePermissions.securityContext.runAsUser }}
        env:
        - name: CHOWN_DIRECTORY
          value: /data/openiam/conf/ai
        volumeMounts:
        - mountPath: /data/openiam/conf/ai
          name: openiam-pvc-storage-machine-learning
      volumes:
      - name: openiam-pvc-storage-machine-learning
        persistentVolumeClaim:
          claimName: openiam-pvc-storage-machine-learning
      - name: vault-server-config
        persistentVolumeClaim:
          claimName: openiam-pvc-vault-server
      - name: vault-client-config
        persistentVolumeClaim:
          claimName: openiam-pvc-vault-client
{{- if .Values.openiam_rabbitmq.rabbitmq.tls.enabled }}
      - name: openiam-pvc-rabbitmq-jks
        persistentVolumeClaim:
          claimName: openiam-pvc-rabbitmq-jks
      - name: rabbitmq-certificates
        secret:
          secretName: rabbitmq-certificates
{{- end }}
