apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openiam.appname }}-freshdesk-connector-rabbitmq
  labels:
{{ include "labels.standard" . | indent 4 }}
  annotations:
  {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    release: {{ .Release.Name }}
    app: {{ .Values.openiam.appname }}-freshdesk-connector-rabbitmq
