apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-extra-config
  labels:
    openiam_collect_logs: 'true'
data:
  extraVHost.conf: |-
{{ .Files.Get ".apache/extraVHost.conf" | indent 4}}
  extraApache.conf: |-
{{ .Files.Get ".apache/extraApache.conf" | indent 4}}