apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  openiamDatabaseUserName: {{ required "openiam.vault.secrets.jdbc.openiam.username is required" .Values.openiam.vault.secrets.jdbc.openiam.username | quote }}
  activitiDatabaseUserName: {{ required "openiam.vault.secrets.jdbc.activiti.username is required" .Values.openiam.vault.secrets.jdbc.activiti.username | quote }}
  groovyDatabaseUserName: {{ required "openiam.vault.secrets.jdbc.groovy.username is required" .Values.openiam.vault.secrets.jdbc.groovy.username | quote }}
  openiamDatabasePassword: {{ required "openiam.vault.secrets.jdbc.openiam.password is required" .Values.openiam.vault.secrets.jdbc.openiam.password | quote }}
  activitiDatabasePassword: {{ required "openiam.vault.secrets.jdbc.activiti.password is required" .Values.openiam.vault.secrets.jdbc.activiti.password | quote }}
  groovyDatabasePassword: {{ required "openiam.vault.secrets.jdbc.groovy.password is required" .Values.openiam.vault.secrets.jdbc.groovy.password | quote }}
  rabbitmqUserName: {{ required "openiam.vault.secrets.rabbitmq.username is required" .Values.openiam.vault.secrets.rabbitmq.username | quote }}
  rabbitmqPassword: {{ required "openiam.vault.secrets.rabbitmq.password is required" .Values.openiam.vault.secrets.rabbitmq.password | quote }}
  rabbitmqJksKeyPassword: {{ .Values.openiam.vault.secrets.rabbitmq.jksKeyPassword | quote }}
  databaseRootUserName: {{ required "openiam.vault.secrets.jdbc.root.user is required" .Values.openiam.vault.secrets.jdbc.root.user | quote }}
  databaseRootPassword: {{ required "openiam.vault.secrets.jdbc.root.password is required" .Values.openiam.vault.secrets.jdbc.root.password | quote }}
  redisPassword: {{ .Values.openiam.vault.secrets.redis.password | quote }}
  redisSentinelPassword: {{ .Values.openiam.vault.secrets.redis.sentinel.password | quote }}
  flywayOpeniamUserName: {{ required "openiam.flyway.openiam.username is required" .Values.openiam.flyway.openiam.username }}
  flywayActivitiUserName: {{ required "openiam.flyway.activiti.username is required" .Values.openiam.flyway.activiti.username }}
  flywayGroovyUserName: {{ required "openiam.flyway.groovy.username is required" .Values.openiam.flyway.groovy.username }}
  flywayOpeniamPassword: {{ required "openiam.flyway.openiam.password is required" .Values.openiam.flyway.openiam.password }}
  flywayActivitiPassword: {{ required "openiam.flyway.activiti.password is required" .Values.openiam.flyway.activiti.password }}
  flywayGroovyPassword: {{ required "openiam.flyway.groovy.password is required" .Values.openiam.flyway.groovy.password }}
  javaKeystorePassword: {{ required "openiam.vault.secrets.javaKeystorePassword is required" .Values.openiam.vault.secrets.javaKeystorePassword }}
  jksPassword: {{ required "openiam.vault.secrets.jks.password is required" .Values.openiam.vault.secrets.jks.password }}
  jksKeyPassword: {{ required "openiam.vault.secrets.jks.keyPassword is required" .Values.openiam.vault.secrets.jks.keyPassword }}
  jksCookieKeyPassword: {{ required "openiam.vault.secrets.jks.cookieKeyPassword is required" .Values.openiam.vault.secrets.jks.cookieKeyPassword }}
  jksCommonKeyPassword: {{ required "openiam.vault.secrets.jks.commonKeyPassword is required" .Values.openiam.vault.secrets.jks.commonKeyPassword }}
  vaultKeyPassword: {{ required "openiam.vault.keypass is required" .Values.openiam.vault.keypass }}
  opensearchUserName: {{ .Values.openiam.vault.secrets.opensearch.username | quote }}
  opensearchPassword: {{ .Values.openiam.vault.secrets.opensearch.password | quote }}
  {{ if .Values.openiam.cassandra.password }}
  cassandraPassword: {{ .Values.openiam.cassandra.password }}
  {{end}}

#IAM-5487 - remove elasticsearchUserName/elasticsearchPassword
