apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-server-config
  labels:
    openiam_collect_logs: 'true'
data:
  vault.crt: |-
{{ .Files.Get ".vault/vault.crt" | indent 4}}
  vault.key: |-
{{ .Files.Get ".vault/vault.key" | indent 4}}
  vault.ca.key: |-
{{ .Files.Get ".vault/vault.ca.key" | indent 4}}