apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openiam.appname }}-rproxy
  labels:
{{ include "labels.standard" . | indent 4 }}
  annotations:
  {{- if and (.Values.openiam.rproxy.aws) (.Values.openiam.rproxy.aws.certificateManagerARN) }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.openiam.rproxy.aws.certificateManagerARN }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  {{- end }}
  {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
{{- if (.Values.openiam.rproxy.loadBalancer.ip) }}
  loadBalancerIP: {{ .Values.openiam.rproxy.loadBalancer.ip }}
{{- end }}
  ports:
{{- if and (.Values.openiam.rproxy.aws) (.Values.openiam.rproxy.aws.certificateManagerARN) }}
  - name: rproxy-https
    port: 443
    protocol: TCP
    targetPort: 80
{{- else if not (eq (int .Values.openiam.rproxy.http) 1 ) }}
  - name: rproxy-https
    port: 443
    protocol: TCP
    targetPort: 443
{{- else }}
  - name: rproxy-http
    port: 80
    protocol: TCP
    targetPort: 80
{{- end }}
  selector:
    release: {{ .Release.Name }}
    app: {{ .Values.openiam.appname }}-rproxy
