{{- if eq (int .Values.openiam_mariadb.mysql.debugclient.enabled) 1 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.openiam.appname }}-mariadb-debugclient
  labels:
    openiam_collect_logs: 'true'
{{ include "labels.standard" . | indent 4 }}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: {{ .Values.openiam.appname }}-mariadb-debugclient
  serviceName: {{ .Values.openiam.appname }}-mariadb-debugclient
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: {{ .Values.openiam.appname }}-mariadb-debugclient
        openiam_collect_logs: 'true'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.openiam.appname }}-mariadb-debugclient
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: mariadb
        image: mariadb:10.4.8
        imagePullPolicy: {{ .Values.openiam.image.pullPolicy }}
        env:
        - name: TZ
          value: {{ .Values.global.timezone | quote }}
        - name: MYSQL_ROOT_PASSWORD
          value: "passwd00"
        readinessProbe:
          exec:
            command: ['/bin/sh', '-c', 'exit 0']
          initialDelaySeconds: 120
          timeoutSeconds: 120
          periodSeconds: 60
          failureThreshold: 6
        livenessProbe:
          exec:
            command: ['/bin/sh', '-c', 'exit 0']
          initialDelaySeconds: 120
          timeoutSeconds: 120
          periodSeconds: 60
          failureThreshold: 6
{{- end }}